name: blockList

on:
  schedule:
    - cron: 0 6 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install IPy requests
    - name: Update blockList
      run: |
        python blockList.py
    - name: Commit changes
      run: |
        git config user.email pybot@github.com
        git config user.name pybot
        git add blockList
        git commit -m "blockList-`date`"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
